services:
  - type: web
    name: safaricomscanner-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DARAJA_CONSUMER_KEY
        sync: false
      - key: DARAJA_CONSUMER_SECRET
        sync: false
